# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1aeb78089c7e841f816c7f76c118f5d9ca70b54324caaa6ea005d96715fe505a53041731d69d25082c6af2ea061f81ee8e26de0cfd46e854ba6dc86108838c6

test:
  secret_key_base: ce7047da29315af34678273dadf7afd88cd0fef6abf33526320d50f3dee3a5518152e4de7f6a561bf98b853829c89c107c690bc12781ad1f4833019bb8214d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
